// Spanish translations for city/country names. Used by apply-es.mjs to localize
// the auto-generated entries in src/data/cities.ts. Only differences from English
// matter; identical names are harmless (filtered when applied).

export const COUNTRY_ES = {
  'Afghanistan': 'Afganistán',
  'Åland Islands': 'Islas Åland',
  'Albania': 'Albania',
  'Algeria': 'Argelia',
  'American Samoa': 'Samoa Americana',
  'Andorra': 'Andorra',
  'Angola': 'Angola',
  'Antigua and Barbuda': 'Antigua y Barbuda',
  'Armenia': 'Armenia',
  'Aruba': 'Aruba',
  'Azerbaijan': 'Azerbaiyán',
  'Bahamas': 'Bahamas',
  'Bahrain': 'Baréin',
  'Bangladesh': 'Bangladés',
  'Barbados': 'Barbados',
  'Belarus': 'Bielorrusia',
  'Belize': 'Belice',
  'Benin': 'Benín',
  'Bermuda': 'Bermudas',
  'Bhutan': 'Bután',
  'Bosnia and Herzegovina': 'Bosnia y Herzegovina',
  'Botswana': 'Botsuana',
  'Brazil': 'Brasil',
  'Brunei': 'Brunéi',
  'Bulgaria': 'Bulgaria',
  'Burkina Faso': 'Burkina Faso',
  'Burundi': 'Burundi',
  'Cabo Verde': 'Cabo Verde',
  'Cambodia': 'Camboya',
  'Cameroon': 'Camerún',
  'Canada': 'Canadá',
  'Cayman Islands': 'Islas Caimán',
  'Central African Republic': 'República Centroafricana',
  'Chad': 'Chad',
  'China': 'China',
  'Comoros': 'Comoras',
  'Cook Islands': 'Islas Cook',
  'Croatia': 'Croacia',
  'Curaçao': 'Curazao',
  'Cyprus': 'Chipre',
  'Democratic Republic of the Congo': 'República Democrática del Congo',
  'Djibouti': 'Yibuti',
  'Dominica': 'Dominica',
  'Dominican Republic': 'República Dominicana',
  'El Salvador': 'El Salvador',
  'Equatorial Guinea': 'Guinea Ecuatorial',
  'Eritrea': 'Eritrea',
  'Estonia': 'Estonia',
  'Eswatini': 'Esuatini',
  'Ethiopia': 'Etiopía',
  'Falkland Islands': 'Islas Malvinas',
  'Faroe Islands': 'Islas Feroe',
  'French Guiana': 'Guayana Francesa',
  'French Polynesia': 'Polinesia Francesa',
  'Gabon': 'Gabón',
  'Gambia': 'Gambia',
  'Georgia': 'Georgia',
  'Ghana': 'Ghana',
  'Gibraltar': 'Gibraltar',
  'Greenland': 'Groenlandia',
  'Guadeloupe': 'Guadalupe',
  'Guam': 'Guam',
  'Guatemala': 'Guatemala',
  'Guinea': 'Guinea',
  'Guinea-Bissau': 'Guinea-Bisáu',
  'Guyana': 'Guyana',
  'Haiti': 'Haití',
  'Holy See': 'Santa Sede',
  'Honduras': 'Honduras',
  'Indonesia': 'Indonesia',
  'Iraq': 'Irak',
  'Isle of Man': 'Isla de Man',
  'Ivory Coast': 'Costa de Marfil',
  'Jamaica': 'Jamaica',
  'Jordan': 'Jordania',
  'Kazakhstan': 'Kazajistán',
  'Kiribati': 'Kiribati',
  'Kuwait': 'Kuwait',
  'Kyrgyzstan': 'Kirguistán',
  'Laos': 'Laos',
  'Latvia': 'Letonia',
  'Lebanon': 'Líbano',
  'Lesotho': 'Lesoto',
  'Liberia': 'Liberia',
  'Libya': 'Libia',
  'Liechtenstein': 'Liechtenstein',
  'Lithuania': 'Lituania',
  'Luxembourg': 'Luxemburgo',
  'Macao': 'Macao',
  'Madagascar': 'Madagascar',
  'Malawi': 'Malaui',
  'Maldives': 'Maldivas',
  'Mali': 'Malí',
  'Malta': 'Malta',
  'Marshall Islands': 'Islas Marshall',
  'Martinique': 'Martinica',
  'Mauritania': 'Mauritania',
  'Mauritius': 'Mauricio',
  'Mayotte': 'Mayotte',
  'Mexico': 'México',
  'Micronesia': 'Micronesia',
  'Moldova': 'Moldavia',
  'Monaco': 'Mónaco',
  'Mongolia': 'Mongolia',
  'Montenegro': 'Montenegro',
  'Mozambique': 'Mozambique',
  'Myanmar': 'Myanmar',
  'Namibia': 'Namibia',
  'New Caledonia': 'Nueva Caledonia',
  'Nicaragua': 'Nicaragua',
  'Niger': 'Níger',
  'North Korea': 'Corea del Norte',
  'North Macedonia': 'Macedonia del Norte',
  'Northern Mariana Islands': 'Islas Marianas del Norte',
  'Oman': 'Omán',
  'Pakistan': 'Pakistán',
  'Palau': 'Palaos',
  'Palestine': 'Palestina',
  'Papua New Guinea': 'Papúa Nueva Guinea',
  'Puerto Rico': 'Puerto Rico',
  'Republic of the Congo': 'República del Congo',
  'Réunion': 'Reunión',
  'Romania': 'Rumanía',
  'Russia': 'Rusia',
  'Rwanda': 'Ruanda',
  'Saint Kitts and Nevis': 'San Cristóbal y Nieves',
  'Saint Lucia': 'Santa Lucía',
  'Saint Vincent and the Grenadines': 'San Vicente y las Granadinas',
  'Samoa': 'Samoa',
  'San Marino': 'San Marino',
  'Sao Tome and Principe': 'Santo Tomé y Príncipe',
  'Senegal': 'Senegal',
  'Serbia': 'Serbia',
  'Seychelles': 'Seychelles',
  'Sierra Leone': 'Sierra Leona',
  'Slovakia': 'Eslovaquia',
  'Slovenia': 'Eslovenia',
  'Solomon Islands': 'Islas Salomón',
  'Somalia': 'Somalia',
  'South Georgia and the South Sandwich Islands': 'Islas Georgias del Sur y Sandwich del Sur',
  'South Sudan': 'Sudán del Sur',
  'Sudan': 'Sudán',
  'Suriname': 'Surinam',
  'Svalbard and Jan Mayen': 'Svalbard y Jan Mayen',
  'Syria': 'Siria',
  'Tajikistan': 'Tayikistán',
  'Tanzania': 'Tanzania',
  'Timor-Leste': 'Timor Oriental',
  'Togo': 'Togo',
  'Tonga': 'Tonga',
  'Trinidad and Tobago': 'Trinidad y Tobago',
  'Tunisia': 'Túnez',
  'Turkmenistan': 'Turkmenistán',
  'Turks and Caicos Islands': 'Islas Turcas y Caicos',
  'Tuvalu': 'Tuvalu',
  'Uganda': 'Uganda',
  'Ukraine': 'Ucrania',
  'United States of America': 'Estados Unidos',
  'Uzbekistan': 'Uzbekistán',
  'Vanuatu': 'Vanuatu',
  'Virgin Islands (US)': 'Islas Vírgenes (EE. UU.)',
  'Western Sahara': 'Sáhara Occidental',
  'Yemen': 'Yemen',
  'Zambia': 'Zambia',
  'Zimbabwe': 'Zimbabue',
};

export const CITY_ES = {
  'Algiers': 'Argel',
  'Phnom Penh': 'Nom Pen',
  'Ndjamena': 'Yamena',
  'Urumqi': 'Urumchi',
  'Addis Ababa': 'Adís Abeba',
  'Tbilisi': 'Tiflis',
  'Baghdad': 'Bagdad',
  'Almaty': 'Almatý',
  'Tripoli': 'Trípoli',
  'Male': 'Malé',
  'Chisinau': 'Chisináu',
  'Ulaanbaatar': 'Ulán Bator',
  'Rangoon': 'Rangún',
  'Muscat': 'Mascate',
  'Bucharest': 'Bucarest',
  'Yekaterinburg': 'Ekaterimburgo',
  'Belgrade': 'Belgrado',
  'Khartoum': 'Jartum',
  'Damascus': 'Damasco',
  'Sanaa': 'Saná',
  'Macau': 'Macao',
};
